from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from datetime import datetime
import os

def generate_pdf(disease, confidence, symptoms, precautions, description, language, session_id):
    os.makedirs('reports', exist_ok=True)
    filename = f"reports/DiagnosBot_Report_{session_id[:8]}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    y = height - 1*inch

    # Header
    c.setFont("Helvetica-Bold", 18)
    c.setFillColorRGB(0.17, 0.48, 0.90)  # blue
    c.drawCentredString(width/2, y, "DiagnosBot v4.0 - Medical Report")
    y -= 30

    c.setFont("Helvetica", 10)
    c.setFillColorRGB(0.4, 0.4, 0.4)
    c.drawCentredString(width/2, y, "AI-Powered Educational Tool • Not Medical Advice")
    y -= 40

    # Report Info
    c.setFont("Helvetica-Bold", 12)
    c.setFillColorRGB(0.17, 0.48, 0.90)
    c.drawString(1*inch, y, "Report Information")
    y -= 25

    c.setFont("Helvetica", 11)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(1*inch, y, f"Date & Time: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
    y -= 20
    c.drawString(1*inch, y, f"Language: {language}")
    y -= 40

    # Diagnosis
    c.setFont("Helvetica-Bold", 14)
    c.setFillColorRGB(0.17, 0.48, 0.90)
    c.drawString(1*inch, y, "Primary Diagnosis")
    y -= 30

    c.setFont("Helvetica-Bold", 20)
    c.setFillColorRGB(0.17, 0.48, 0.90)
    c.drawCentredString(width/2, y, disease)
    y -= 40

    # Confidence
    c.setFont("Helvetica", 12)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(1*inch, y, f"Confidence Score: {confidence:.1f}%")
    y -= 40

    # Symptoms
    c.setFont("Helvetica-Bold", 12)
    c.setFillColorRGB(0.17, 0.48, 0.90)
    c.drawString(1*inch, y, "Reported Symptoms")
    y -= 25
    c.setFont("Helvetica", 11)
    for sym in symptoms:
        c.drawString(1.2*inch, y, f"• {sym.replace('_', ' ').title()}")
        y -= 18
    y -= 20

    # Precautions
    if precautions:
        c.setFont("Helvetica-Bold", 12)
        c.setFillColorRGB(0.17, 0.48, 0.90)
        c.drawString(1*inch, y, "Recommended Precautions")
        y -= 25
        c.setFont("Helvetica", 11)
        for i, prec in enumerate(precautions, 1):
            c.drawString(1.2*inch, y, f"{i}. {str(prec).capitalize()}")
            y -= 18
        y -= 20

    # Disclaimer
    c.setFont("Helvetica-Bold", 10)
    c.setFillColorRGB(0.7, 0.3, 0)
    disclaimer = (
        "⚠️  IMPORTANT DISCLAIMER: This report is generated by an AI system for "
        "educational purposes only. It does not constitute medical advice, "
        "diagnosis, or treatment. Always consult a qualified healthcare professional."
    )
    c.drawString(1*inch, y, disclaimer[:100])
    y -= 18
    if len(disclaimer) > 100:
        c.drawString(1*inch, y, disclaimer[100:])

    c.save()
    return filename
